
import platform

platform_word = platform.system()
platform_char = platform_word[0].lower()

if platform_char == 'w':
    # windows
    from distutils.core import setup
    import py2exe

    setup(console=['finda.py'],
          packages=['finda'],

          # single executable
          options={'py2exe': {'bundle_files': 1}},
          zipfile=None
          )

elif platform_char == 'd':
    # mac
    """
    This is a setup.py script generated by py2applet
    
    Usage:
        python setup.py py2app
    """

    from setuptools import setup

    import py2app

    APP = ['finda.py']
    DATA_FILES = []
    OPTIONS = {'argv_emulation': True}

    setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
    )
